import { Category, EducationQualification, Gender, Title } from "../enum/employee.enum";

export interface IEmployee {
  id?: string;
  title?: Title;
  firstName?: string;
  lastName?: string;
  designationName?: string;
  designationId?: string;
  employeeDepartmentId?: string;
  employeeDepartmentName?: string;
  mobileNumber?: string;
  companyName?: string;
  companyId?: string;
  recruitedBy?: string;
  gender?: Gender;
  fatherName?: string;
  motherName?: string;
  husbandName?: string | null;
  category?: Category;
  dateOfBirth?: string;
  age?: number;
  dateOfJoining?: string;
  highestEducationQualification?: EducationQualification;
  bloodGroup?: string;
  permanentAddress?: string;
  presentAddress?: string;
  city?: string;
  district?: string;
  state?: string;
  pincode?: number;
  referenceName?: string;
  referenceAddress?: string;
  referenceNumber?: string;
  bankAccountNumber?: string;
  ifscCode?: string;
  bankCity?: string;
  bankName?: string;
  pfUanNumber?: string;
  esicNumber?: string;
  policeVerificationNumber?: string;
  policeVerificationDate?: string;
  trainingCertificateNumber?: string;
  trainingCertificateDate?: string;
  medicalCertificateNumber?: string;
  medicalCertificateDate?: string;
  photoUpload?: string;
  aadhaarUpload?: string;
  panCardUpload?: string;
  bankPassbook?: string;
  markSheet?: string;
  otherDocument?: string;
  salary?: number;
  aadhaarNumber?: string;
}
